# Generated by Django 5.2.6 on 2025-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('projects', '0002_alter_project_description_remove_project_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='projects', to='languages.language'),
        ),
    ]
