# Generated by Django 5.2.6 on 2025-10-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='creator',
            new_name='owner',
        ),
    ]
