# Generated by Django 5.2.6 on 2025-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(null=True, related_name='projects', to='languages.language'),
        ),
    ]
