# Generated by Django 5.2.6 on 2025-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='../default_image_nyj9lt', upload_to='images/'),
        ),
    ]
