# Generated by Django 5.2.6 on 2025-10-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_thumbnail_alter_project_live_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
