# Generated by Django 5.2.6 on 2025-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('projects', '0007_project_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='languages.language'),
        ),
    ]
