# Generated by Django 5.2.6 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
        ('libraries', '0001_initial'),
        ('projects', '0009_alter_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='frameworks.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='projects', to='libraries.library'),
        ),
    ]
