# Generated by Django 5.2.6 on 2025-09-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_pfhq2q', null=True, upload_to='images/'),
        ),
    ]
